config/routes.rb
Rails.application.routes.draw do

  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  status     :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  belongs_to :user
  # if delete an order it will delete the line items asscoiated with it from the db
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

#create array line items
# sums the total_cost as calculated in line_items.rb
  def total_cost
    line_items.to_a.sum {|item| item.total_cost}
  end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @customer_order = Order.find params[:id]
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
  end

  def edit
    @order = Order.find params[:id]
  end

  def update
    order = Order.find params[:id]
    order.update order_params
    redirect_to #the page that you were on
  end

  def destroy
    @order = Order.find params[:id]
    @order.destroy if @order.id == session[:order_id]
    session[:order_id] = nil

    respond_to do |format|
      format.html {redirect_to root_path}
    end

    # redirect_to shop_path
    #the page that you were on
  end

  def remove_item product_id, order_item
    order_item.delete(product_id)
  end


  private

  def order_params
    params.require(:order).permit(:user_id, :status, :id)
  end

end

app/views/orders/_show_order.html.erb
<table class="table table-striped table-hover">

  <tr>
    <td> </td>
    <td>Product</td>
    <td>Size</td>
    <td>Unit Price</td>
    <td>Quantity</td>
    <td>Total Price</td>
    <td> </td>
  </tr>

  <% @order.line_items.each do |item| %>
    <tr>
      <td><%= item.product.images[0] %></td>
      <td><%= item.product.name %></td>
      <td><%= item.product.size %></td>
      <td><%= number_to_currency(item.product.cost) %></td>
      <td><%= item.quantity %></td>
      <td><%= number_to_currency(item.quantity * item.product.cost) %></td>
    </tr>
  <% end %>

      <tr>
        <td colspan="5" ></td>
        <td colspan="2" class="totalCost"><%= number_to_currency(@order.total_cost) %></td>
      </tr>

</table>

app/views/orders/index.html.erb
<div class="container">
  <%=  render :partial => 'layouts/navbarInner' %>
  <h1>Listing Orders</h1>

  <table class=table>
    <thead>
      <tr>
        <td>ORDER ID</td>
        <td>STATUS</td>
        <td>USER ID</td>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%=link_to "#{order.id}", order_path(order.id) %></td>
          <td><%= order.status %> </td>
          <td><%= order.user_id %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/orders/show.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

    <div class="CartContainer">
   	   <div class="Header">
   	   	<h3 class="Heading">Shopping Cart</h3>
   	   	<h5 class="Action"><%= link_to 'Empty cart', @order, method: :delete, data: {confirm: 'Are you sure you want to empty your cart?'}, :class=>"remove" %></h5>
   	   </div>
   <% @customer_order.line_items.each do |item| %>
   	   <div class="Cart-Items">
   	   	  <div class="image-box">
            <%= cl_image_tag(item.product.attachment.key, :style => "height:150px") %>
   	   	  </div>

   	   	  <div class="about">
       
   	   	  	<h1 class="title"><%= item.product.name %></h1>
   	   	  	<h3 class="subtitle"><%= item.product.size %></h3>
   	   	  	<%# <img src="images/veg.png" style={{ height="30px" }}/> %>
   	   	  </div>
   	   	  <div class="counter">
   	   	  	<div class="order-btn">+</div>
   	   	  	<div class="count"><%= item.quantity %></div>
   	   	  	<div class="order-btn">-</div>
   	   	  </div>
   	   	  <div class="prices">
   	   	  	<div class="amount"><%= number_to_currency(item.product.cost) %></div>
   	   	 
   	   	  	<div class="remove-b"><%= link_to 'Remove', lineitem_destroy_path(item.id), :method => 'delete' %></div>
   	   	  </div>
          </div>
<% end %>
   	 <hr> 
   	 <div class="checkout">
   	 <div class="total">
   	 	<div>
   	 		<div class="Subtotal">Sub-Total</div>
   	 		<div class="items"><%= LineItem.all.size%> items</div>
   	 	</div>
   	 	<div class="total-amount"><%= number_to_currency(@order.total_cost) %></div>
   	 </div>
   	 <button class="button"><%= link_to "Checkout", new_order_charge_path(:order_id => @order.id) %></button></div>
   </div>