config/routes.rb
Rails.application.routes.draw do

  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  gender     :string
#

class Category < ActiveRecord::Base
  has_and_belongs_to_many :products

  def name_of_cat
  "#{name}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update category_params
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path

  end

  private

  def category_params
    params.require(:category).permit(:name, :gender)
  end

end

app/views/categories/_form.html.erb
<%= form_for(@category, :html=>{:multipart=>true}) do |f| %>
  <div class="row">
    <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="form-group">
          *<%= f.label :name %>
          <%= f.text_field :name, :autofocus=>true, :required => true, :class=>"form-control textfield-border" %>
        </div>
<% end %>
      </div>
      <div class="col-md-3"></div>
</div>

app/views/categories/_list.html.erb
<br>
<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th></th>
    <th></th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.gender %></td>
      <td><%= link_to "Edit", edit_category_path(:id => category.id)%></td>
      <td><%= link_to "Delete", category_path(:id => category.id), :method=>'delete', data: { confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>
</table>

app/views/categories/edit.html.erb
<%=  render :partial => 'layouts/navbarInner' %>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-4">
    <h1>Edit Category</h1>
    <%= form_for @category do |f| %>
      <div class="form-group">
        *<%= f.label :name %>
        <%= f.text_field :name, :class => "textfield-border form-control", :required => true %>
      </div>
      <div class="form-group">
          *<%= f.label :gender %>
          <%= f.select :gender, [['women'],['men'],['unisex']], :include_blank => false, :required => true %>
      </div>
      <%= submit_tag 'Edit Category', :class => 'btnborder btn btn-primary'%>
    <% end %>
  </div>
  <div class="col-md-1"></div>
  <div class="col-md-5"></div>
  <div class="col-md-1"></div>
</div>

app/views/categories/index.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-5">
    <div class="row">
      <div class="col-md-11">
        <h1>All Categories</h1>
      <%=  render :partial => 'categories/list' %>
      </div>
      <div class="col-md-1"></div>
    </div>
  </div>
  <div class="col-md-5">

  </div>
  <div class="col-md-1"></div>
</div>

app/views/categories/new.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-5">
    <div class="row">
      <div class="col-md-11">
        <h1>New Category</h1>
        <br>
        <%= form_for @category do |f| %>
          <div class="form-group">
            *<%= f.label :name %>
            <%= f.text_field :name, :class => "textfield-border form-control", :required => true %>
          </div>
          <div class="form-group">
              *<%= f.label :gender %>
              <%= f.select :gender, [['women'],['men'],['unisex']], :include_blank => false, :required => true %>
          </div>
          <%= submit_tag 'New Category', :class => 'btnborder btn btn-primary', :id =>'btnblack'%>
        <% end %>
      </div>
      <div class="col-md-1"></div>
    </div>
  </div>
  <div class="col-md-5">
  
  </div>
  <div class="col-md-1"></div>
</div>

app/views/categories/show.html.erb
<%=  render :partial => 'layouts/navbarInner' %>
<h1>Category</h1>
<ul>
    <li> <%= @category.name %> </li>
    <%= link_to "Edit", edit_product_category_path(@category.id)%>
    <%= link_to "Delete", product_category_path(@category.id),
                                  :method=>"delete", :data=>{:confirm=>"Are you sure?"} %>

</ul>