config/routes.rb
Rails.application.routes.draw do

  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  cost       :integer
#  size       :string
#  color      :string
#  gender     :string
#  brand      :text
#  info       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :text
#  images     :text             default("{}"), is an Array
#

class Product < ActiveRecord::Base

  has_many :favourites
  has_many :reviews
  has_many :line_items, dependent: :destroy
  has_and_belongs_to_many :categories
  has_one_attached :attachment

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all


  end

  def search
    @products = Product.where :gender => params[:gender]
  end

  def show
    @user = @current_user
    @product = Product.find params[:id]
    session[:prev_url]= request.referer
  end

  def new
    @products = Product.all
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
  
    if @product.save
      flash[:create] = "Product created successfully"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    session[:prev_url]= request.referer
  end

  def update
 
    
    @product = Product.new(product_params)
    @product.update(product_params)

    if @product.save
      flash[:create] = "Product updated successfully"
      redirect_to session.delete(:prev_url)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      
    else
      redirect_to session.delete(:prev_url)
    end
    # respond_to do |format|
    #   format.html { redirect_to session.delete(:prev_url) , notice: 'Product is successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit(:name, :cost, :size, :color, :gender, :brand, :info, :attachment, :category_ids)
  end

end

app/views/products/_form2.html.erb
<div class="row">


<div class="col-md-11">
<%= form_for(@product, :html=>{:multipart=>true}) do |f| %>

<div class="form-group">
  *<%= f.label :name %>
  <%= f.text_field :name, :autofocus=>true, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :cost %>
  <%= f.number_field :cost, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :size %>
  <%= f.text_field :size, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :color %>
  <%= f.text_field :color, :required => true, :class=>"form-control textfield-border" %>
</div>

<div class="form-group">
  *<%= f.label :brand %>
  <%= f.text_field :brand, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :info %>
  <%= f.text_field :info, :required => true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
  *<%= f.label :attachment %>
  <%= f.file_field :attachment, direct_upload: true, :class=>"form-control textfield-border" %>
</div>
<div class="form-group">
    *<%= f.label :gender %>
    <%= f.select :gender, [['women'],['men'],['unisex']], :include_blank => false, :required => true %>
</div>
<div class="form-group">

    *<%= f.label :category %>
    <%= f.collection_select :category_ids, Category.all, :id, :name, :multiple => true, :prompt => 'Select'%>
</div>
<div class="button-center">
  <%= f.submit 'Submit', :class=>"btnblack btnborder btn btn-primary" %>
</div>
<% end %>

</div>
<div class="col-md-1"></div>
</div>

app/views/products/_list.html.erb
<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th></th>
      <th></th>
  </tr>
<% @products.each do |p| %>
<tr>
  <td>
    <%= link_to p.name, product_path(p.id) %>
  </td>
  <td>

    <%if p.gender == "women"%>
    F
    <% else %>
    M
    <% end %>
  </td>
  <td>
    <%= link_to "Edit", edit_product_path(p.id)%>
  </td>
  <td>
    <%= link_to "Delete", product_path(p.id),
                                  :method=>"delete", :data=>{:confirm=>"Are you sure?"} %>
  </td>
  </div>
</tr>

<% end %>
</table>

app/views/products/edit.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-5">
    <h1>Edit product</h1>
    <% if @product.errors.any? %>
      <ol>
      <% @product.errors.full_messages.each do |msg| %>
        <li class="bg-danger"><%= msg %></li>
      <% end %>
      </ol>
    <% end %>
    <%= render :partial=>"form2" %>
  </div>
  <div class="col-md-6"></div>
</div>

app/views/products/index.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">

  <div class="col-md-1"></div>

    <div class="col-md-5">
      <h1>All Products</h1>
      <%=  render :partial => 'products/list' %>
    </div>
  <div class="col-md-5">

  </div>
  <div class="col-md-1"></div>
</div>

app/views/products/new.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<div class="row">

  <div class="col-md-1"></div>

    <div class="col-md-5">
      <h1>New Product</h1>
        <% if @product.errors.any? %>
          <ol>
          <% @product.errors.full_messages.each do |msg| %>
            <li class="bg-danger"><%= msg %></li>
          <% end %>
          </ol>
        <% end %>

      <%= render :partial => "form2" %>

    </div>
  <div class="col-md-5">
    
  </div>
  <div class="col-md-1"></div>
</div>

app/views/products/show.html.erb
<%=  render :partial => 'layouts/navbarInner' %>

<section class="product-container">
 
  <div class="left-product">
   <%= cl_image_tag(@product.attachment.key, :type => :upload, class: "active" )  %>
  </div>
 
  <div class="right-column">
 
    <div class="product-description">
      <span><h3><%= @product.name %></h3></span>
      <h1><%= @product.brand %></h1>
      <p>Hot Fashion Men′s Jeans Pants Printed Design Casual, Biker Badges Brushed Denim Pants Jeans</p>
    </div>
 
    <div class="product-configuration">
 
     <div class="product-color">
        <span>Color</span>
 
        <div class="color-choose">
          <div>
            <input data-image="red" type="radio" id="red" name="color" value="red" checked>
            <label for="red"><span></span></label>
          </div>
          <div>
            <input data-image="blue" type="radio" id="blue" name="color" value="blue">
            <label for="blue"><span></span></label>
          </div>
          <div>
            <input data-image="black" type="radio" id="black" name="color" value="black">
            <label for="black"><span></span></label>
          </div>
        </div>
 
 
      </div>
 
     <div class="product-price">
      <span><%= number_to_currency(@product.cost)%></span>
      <% if @current_user.present? %>
        <div class="buttons-wrapper">
         <%= link_to "Add to Cart", product_line_items_path(product_id: @product.id), :method=>"post", :class=>"product-btn-add" %>
      

          <% if @current_user.already_likes?(@product) %>
            <%= link_to "Remove from Wishlist", product_favourite_path(:product_id=>@product.id, :user_id=>@current_user.id),
                                  :method=>"delete", :class=>"product-btn-add "%>
          <% else %>

            <%= link_to "Add to Wishlist", product_favourites_path(:product_id=>@product.id, :user_id=>@current_user.id),
                                  :method=>"post", :class=>"product-btn-add " %>

          <% end %>
        </div>
        <% end %>
    </div>
  </div>

     <div class="cable-config">
   <h4><strong>Reviews</strong></h4>
     <% if @current_user.present? %>
      <%= form_for([@product, @product.reviews.build]) do |f| %>
        <%= hidden_field_tag :user_id, @current_user.id %>
        <div class="form-review">
          <% if flash[:review_error].present? %>
            <p class="bg-danger"><%= flash[:review_error] %></p>
          <% end %>
          <%= f.text_area :desc, :class=>"form-control review-text"  %>
          <%= f.submit 'Add Review', :class=>"review-button" %>
        </div>
      <% end %>
    <% end %>
    <div class="review-text">
    <% @product.reviews.each do |review| %>
      <p><i class="fa fa-comment-o" aria-hidden="true"></i>
        <%= @user.name%>: <%= review.desc %>
      </p>
    <% end %>
    </div>
    </div>

    </div>
</section>

<script>
$(document).ready(function() {
 
  $('.color-choose input').on('click', function() {
      var productColor = $(this).attr('data-image');
 
      $('.active').removeClass('active');
      $('.left-product img[data-image = ' + productColor + ']').addClass('active');
      $(this).addClass('active');
  });
 
});
</script>