config/routes.rb
Rails.application.routes.draw do

  get 'chatbot/show' => 'chatbot#show'

  root :to => 'pages#home'
  get '/shop/:gender' => 'pages#shop', :as => 'shop'
  get '/shop/:gender/:category' => 'pages#category', :as => 'products_category'

  get '/products/gender/:gender' => 'products#search'

  get'/wishlist' => 'users#wishlist', :as => 'wishlist'

  resources :users
  resources :categories
  resources :products do
    resources :favourites
    resources :reviews
    resources :images
    resources :line_items
  end

  delete '/line_items/:id' => 'line_items#destroy', :as => 'lineitem_destroy'

  resources :orders do
    resources :charges
  end

  get '/thanks' => 'charges#thanks'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/views/layouts/_navbarHomepage.html.erb
<nav class="navbar-inner navbar navbar-fixed-top navbar--color--secondary navbar--size--md" data-startcolor="navbar--color--ghost" data-startsize="navbar--size--xl" data-intocolor="navbar--color--secondary" data-intosize="navbar--size--md">
<div class="container">

<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobileNav" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <%= link_to "Top Shop", root_path, :class => " brandphoto navbar-brand" %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="mobileNav">
  <ul class="nav navbar-nav navbar-right">
    <% if !@current_user.present? %>
    <li>
      <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
    </li>
    <li>
      <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
    </li>

    <li><%= link_to "Join", new_user_path, :class => "blackfont" %></li>
    <!-- <li><%= link_to "Sign in", login_path, :class => "blackfont" %></li> -->
    <li class="dropdown">
      <a href="#" class="dropdown-toggle blackfont" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
      <ul id="login-dp" class="dropdown-menu">
      <li>
        <div class="row">
          <div class="col-md-12">
            <%= form_tag login_path, :class => 'form', :id => 'login-nav' do %>
              <div class="form-group">
                <label class="sr-only" for="exampleInputEmail2">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
              </div>
              <div class="form-group">
                 <label class="sr-only" for="exampleInputPassword2">Password</label>
                 <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
              </div>
              <div class="form-group">
                 <button id="btn-login" type="submit" class="btn btn-primary btnborder btn-block">Sign in</button>
              </div>
            <% end %>
          </div>
         </div>
        </li>
      </ul>
    </li>

    <% end %>

    <% if @current_user.present? %>
    

      <li class=" dropdown">
        <a href="#" class="blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= "#{@current_user.name}" %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu" >
          <li ><%= link_to "Wishlist", wishlist_path, :id=>"drop" %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Edit profile", edit_user_path(@current_user.id), :id=>"drop" %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Logout", login_path, :method => 'delete', :id=>"drop" %></li>
        </ul>
      </li>
    <% end %>

    <% if @current_user.present? %>
    <% if @current_user.admin %>
        <li class=" dropdown">
          <a href="#" class=" blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Products", products_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Product", new_product_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "All Categories", categories_path %></li>
          <li role="separator" class="divider"></li>

          <li><%= link_to "New Category", new_category_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Users", users_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Orders", orders_path %></li>
        </ul>
      </li>
      <% end %>

      <li >
        <%= link_to order_path(:id => @order.id) do%><i id="cart-icon" class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i><% end %>
        <p><%=%>
      </li>

    <% end %>



  </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbarInner.html.erb
<nav class="navbar navbar-fixed-top navbar--color--secondary navbar--size--md navbar-inner" data-startcolor="navbar--color--ghost" data-startsize="navbar--size--xl" data-intocolor="navbar--color--secondary" data-intosize="navbar--size--md">
<div class="container">

<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobileNav" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <%= link_to "Top Shop", root_path, :class => "brandphoto navbar-brand" %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="mobileNav">
  <ul class="nav navbar-nav navbar-right">

    <% if !@current_user.present? %>
     <li class="<%= is_active?(shop_path(:gender => 'men')) %>">
      <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
    </li>
    <li class="<%= is_active?(shop_path(:gender => 'women')) %>">
      <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
    </li>
     <li class="<%= is_active?(new_user_path) %>">
    <%= link_to "Join", new_user_path, :class => "blackfont" %>
    </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle blackfont" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
      <ul id="login-window" class="dropdown-menu">
      <li>
        <div class="row">
          <div class="col-md-12">
            <%= form_tag login_path, :class => 'form', :id => 'login-nav' do %>
              <div class="form-group">
                <label class="sr-only" for="exampleInputEmail2">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
              </div>
              <div class="form-group">
                 <label class="sr-only" for="exampleInputPassword2">Password</label>
                 <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
              </div>
              <div class="form-group">
                 <button type="submit" class="btn btn-primary btnborder btn-block">Sign in</button>
              </div>
            <% end %>
          </div>
         </div>
        </li>
      </ul>
    </li>
  <% end %>

    <% if @current_user.present? %>

     
     <li class="<%= is_active?(shop_path(:gender => 'men')) %>">
        <%= link_to "Men", shop_path(:gender => 'men'), :class => "blackfont"%>
      </li>

      <li class="<%= is_active?(shop_path(:gender => 'women')) %>">                                                    
        <%= link_to "Women", shop_path(:gender => 'women'), :class => "blackfont"%>
      </li>

     
        <li>  
        <a href="#" class="blackfont main-class dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= "#{@current_user.name}" %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Wishlist", wishlist_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Edit profile", edit_user_path(@current_user.id) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Logout", login_path, :method => 'delete' %></li>
        </ul>
      </li>
    <% end %>

    <% if @current_user.present? %>
    <% if @current_user.admin %>
      <li class=" dropdown">
        <a href="#" class=" blackfont dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Products", products_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Product", new_product_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "All Categories", categories_path %></li>
          <li role="separator" class="divider"></li>

          <li><%= link_to "New Category", new_category_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Users", users_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Orders", orders_path %></li>
        </ul>
      </li>
      <% end %>
      <li class="fa-stack fa has-badge <%= is_active?(order_path(:id => @order.id)) %>" data-count=<%= LineItem.all.size%>>
        <%= link_to order_path(:id => @order.id) do%><i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i><% end %>
      </li>
    <% end %>
    </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get Fashions</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/imask/3.4.0/imask.min.js"></script>

   <script type="text/javascript">

   </script>
</head>
<body>

<body class="<%= params[:controller] %> <%=params[:action]%>">

<div class='spacer'></div>
  <div>
  <% if notice %>
    <h6 class="alert alert-success text-center msg"><%= flash[:notice]%></h6>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger text-center msg"><%= alert %></p>
  <% end %>
  </div>
<!-- End of ChatBot code -->
<%= yield %>
</body>
</html>